lab-64/split-the-bill-server

README.md
authentication/cookies.go
authentication/password.go
go.mod
go.sum
handler/handler.go
main.go
main_test.go
router/router.go
storage/database/database.go
storage/database/model.go
storage/ephemeral/ephemeral.go
storage/ephemeral/ephemeral_test.go
storage/storage.go
types/authentication_cookie.go
types/user.go
wire/credentials.go
wire/user.go

Add reworked authentication system

Rework authentication

---

main.go

**Review #23 first.**
- logger initialization had to be moved before the router setup to work correctly
Closes #24

24: Setup logger

---

Dockerfile
Makefile
docker-compose.yml

#22 Enable live reload for docker

---

storage/database/entity/auth_cookie.go
storage/database/entity/credentials.go

40: Fix belongs-to relationship for AuthCookie and Credentials

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
handler/user_handler.go
router/router.go
service/impl/user_service.go
service/user_service_inf.go
storage/database/user_storage.go
storage/ephemeral/test/user_storage_test.go
storage/ephemeral/user_storage.go
storage/user_storage_inf.go

30: Revisit user storage

---

storage/database/db_storages/group_storage.go

58: Fix get group by ID storage function

---

core/response.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
presentation/dto/general_response.go

73: Remove 'Status' from GeneralResponseDTO

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/service/impl/group_service.go
domain/service/service_inf/group_service_inf.go
presentation/handler/group_handler.go
presentation/handler/messages.go
presentation/router/router.go
storage/database/db_storages/group_storage.go
storage/database/entity/group.go
storage/ephemeral/eph_storages/group_storage.go
storage/storage_inf/group_storage_inf.go

76: Add get groups by user endpoint

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/model/test/user.go
domain/model/user.go
domain/service/impl/group_service.go
domain/service/impl/user_service.go
domain/service/service_inf/user_service_inf.go
presentation/dto/credentials.go
presentation/dto/group.go
presentation/dto/user.go
presentation/handler/user_handler.go
presentation/router/router.go
storage/database/db_storages/user_storage.go
storage/database/entity/user.go
storage/ephemeral/eph_storages/test/user_storage_test.go
storage/ephemeral/eph_storages/user_storage.go
storage/storage_inf/user_storage_inf.go

75: Replace username with email

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/model/invitation.go
domain/service/impl/invitation_service.go
domain/service/service_inf/invitation_service_inf.go
presentation/dto/invitation.go
presentation/handler/invitation_handler.go
presentation/router/router.go
storage/database/db_storages/group_storage.go
storage/database/db_storages/invitation_storage.go
storage/ephemeral/eph_storages/group_storage.go
storage/ephemeral/eph_storages/invitation_storage.go
storage/storage_inf/group_storage_inf.go
storage/storage_inf/invitation_storage_inf.go

60, 52: Refactor invitations

---

domain/service/impl/user_service.go
domain/service/service_inf/user_service_inf.go
presentation/handler/user_handler.go

80: Return userDTO on login

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/model/bill.go
presentation/dto/bill.go
storage/database/entity/bill.go

97: Add groupID to bill output DTO

---

domain/model/group.go
domain/model/group_test.go
domain/service/impl/bill_service_test.go
domain/service/impl/group_service.go
domain/service/impl/group_service_test.go
domain/service/impl/setup_test.go
presentation/dto/group.go
storage/mocks/group_storage_mock.go

101 Calculate group balance

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/model/bill.go
domain/model/bill_test.go
domain/model/group.go
domain/model/group_test.go
domain/service/impl/bill_service.go
presentation/dto/bill.go

#119 Add bill balance calculation

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/model/group.go
domain/model/invitation.go
domain/service/impl/group_service.go
domain/service/impl/invitation_service.go
domain/service/impl/setup_test.go
domain/service/invitation_service_inf.go
integration_tests/bill_integration_test.go
integration_tests/seed.go
integration_tests/setup_test.go
integration_tests/user_integration_test.go
main.go
main_test.go
presentation/dto/group.go
presentation/dto/invitation.go
presentation/handler/group_handler.go
presentation/handler/invitation_handler.go
presentation/middleware/authentication.go
presentation/router/router.go
storage/database/db_storages/invitation_storage.go
storage/database/db_storages/user_storage.go
storage/database/db_storages/user_storage_test.go
storage/database/entity/group.go
storage/database/entity/invitation.go
storage/database/entity/user.go
storage/ephemeral/eph_storages/invitation_storage.go
storage/invitation_storage_inf.go

124 handle group invitation from link

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/model/bill.go
domain/model/group.go
domain/model/user.go
presentation/dto/user.go
storage/database/db_storages/bill_storage.go
storage/database/db_storages/group_storage.go
storage/database/db_storages/invitation_storage.go
storage/database/db_storages/user_storage.go
storage/database/db_storages/user_storage_test.go
storage/database/entity/bill.go
storage/database/entity/group.go
storage/database/entity/invitation.go
storage/database/entity/item.go
storage/database/entity/user.go
storage/ephemeral/eph_storages/user_storage.go

Merge before #127 
Closes #126

126 add bill balance to get group and get groupid endpoint

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/model/group.go
domain/model/group_test.go
domain/service/bill_service_inf.go
domain/service/group_service_inf.go
domain/service/impl/bill_service.go
domain/service/impl/bill_service_test.go
domain/service/impl/group_service.go
domain/service/impl/group_service_test.go
domain/service/impl/user_service.go
domain/service/mocks/user_service_mock.go
domain/service/user_service_inf.go
presentation/handler/bill_handler.go
presentation/handler/group_handler.go
presentation/handler/user_handler.go

Authorization is handled as described in the related issue #48 .
Closes #48

48 implement an authorization mechanism

---

presentation/handler/bill_handler.go
presentation/handler/group_handler.go
presentation/handler/messages.go
presentation/handler/user_handler.go

#140 Add unauthorized status codes

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/service/group_service_inf.go
domain/service/impl/group_service.go
domain/service/impl/group_service_test.go
domain/service/mocks/group_service_mock.go
presentation/handler/group_handler.go
presentation/handler/messages.go
presentation/router/router.go
storage/database/db_storages/group_storage.go
storage/database/db_storages/group_storage_test.go
storage/database/db_storages/setup_test.go
storage/database/db_storages/user_storage_test.go
storage/database/entity/base.go
storage/database/entity/bill.go
storage/database/entity/group.go
storage/database/entity/item.go
storage/database/entity/user.go
storage/ephemeral/eph_storages/group_storage.go
storage/group_storage_inf.go
storage/mocks/group_storage_mock.go

#106 Add delete group endpoint

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/service/bill_service_inf.go
domain/service/impl/bill_service.go
presentation/handler/bill_handler.go
presentation/handler/messages.go
presentation/router/router.go
storage/bill_storage_inf.go
storage/database/db_storages/bill_storage.go
storage/ephemeral/eph_storages/bill_storage.go
storage/mocks/bill_storage_mock.go

107 Add delete billid endpoint

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/service/impl/user_service.go
domain/service/mocks/user_service_mock.go
domain/service/user_service_inf.go
presentation/handler/messages.go
presentation/handler/user_handler.go
presentation/router/router.go
storage/cookie_storage_inf.go
storage/database/db_storages/cookie_storage.go
storage/ephemeral/eph_storages/cookie_storage.go
storage/errors.go
storage/mocks/cookie_storage_mock.go

I decided to use a POST `/api/user/logout` endpoint to handle user logout. To perform this request, the user has to be logged in, its authentication cookie will be extracted from the request and deleted from the storage.

141 Logout

---

domain/service/impl/user_service.go
storage/database/entity/user.go

#146 Refactor update username and profile image

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/service/group_service_inf.go
domain/service/impl/group_service.go
domain/service/mocks/group_service_mock.go
domain/util/transaction.go
domain/util/transaction_test.go
presentation/dto/group.go
presentation/handler/group_handler.go

Closes #129 
I implemented the algorithm which creates transactions between a debtor and a creditor to clear the group balance. The implemented function should be optimal, so that the number of transactions needed to balance out the group is minimal. 
Test to check the functionality are given in transaction_test.go

129 Clear debts

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
domain/model/bill.go
domain/service/bill_service_inf.go
domain/service/impl/bill_service.go
domain/service/impl/bill_service_test.go
integration_tests/bill_integration_test.go
presentation/dto/bill.go
presentation/dto/bill_test.go
presentation/handler/bill_handler.go

First review #128 
Closes #113 
It is now only possible to change some specific bill fields (name, date, unseenFrom) on bill update.

113 Add id to iteminputdto

---

.well-known/assetlinks.json
presentation/router/router.go

#166 Add Android Deeplink

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
presentation/handler/bill_handler.go

169: Add GET /api/bill return type in swagger

---

domain/model/bill_test.go
domain/model/group.go
domain/model/group_test.go
domain/service/impl/group_service.go

158: Sort group bills by date

---

domain/service/bill_service_inf.go
domain/service/impl/bill_service.go
presentation/handler/bill_handler.go

176: Fix GET api/bills bool params & unseen_bills on bill creation
